version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/platform/influxdb"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/platform/grafana"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/platform/nodered/runtime"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/platform/nodered"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/platform/nodered"
    schedule:
      interval: weekly
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "pip"
    directory: "/IA-integration/ia-consumer"
    schedule:
      interval: weekly
  - package-ecosystem: "pip"
    directory: "/IA-integration/raspi-simulator"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/IA-integration/ia-consumer"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/IA-integration/raspi-simulator"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
