apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-consumer
  namespace: ot-namespace
  labels:
    app: ia-consumer
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ia-consumer
  template:
    metadata:
      labels:
        app: ia-consumer
    spec:
      containers:
        - name: ia-consumer
          image: ghcr.io/davidevaloroso-sys/ot-security:ia-consumer-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MQTT_BROKER
              value: "mosquitto"
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mosquitto-credentials
                  key: username
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mosquitto-credentials
                  key: password
            - name: MQTT_CLIENT_ID
              value: "ia-consumer-1"
            - name: MQTT_TOPIC_TEMP
              value: "lab/raspi1/temperature"
            - name: MQTT_TOPIC_HUM
              value: "lab/raspi1/humidity"
            - name: MQTT_ALERT_TOPIC
              value: "lab/raspi1/anomaly"
            - name: ANOMALY_THRESHOLD
              value: "0.70"
            - name: MODEL_PATH
              value: "/app/model_random_forest.joblib"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true