apiVersion: apps/v1
kind: Deployment
metadata:
  name: ot-mqtt-consumer
  namespace: ot-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ot-mqtt-consumer
  template:
    metadata:
      labels:
        app: ot-mqtt-consumer
    spec:
      containers:
        - name: ot-mqtt-consumer
          image: ghcr.io/davidevaloroso-sys/ot-security:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MQTT_BROKER
              value: "192.168.1.XX"
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_TOPIC
              value: "lab/#"
            - name: MQTT_CLIENT_ID
              value: "ot-mqtt-consumer"
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-credentials
                  key: username
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: ot-mqtt-consumer
  namespace: ot-namespace
spec:
  selector:
    app: ot-mqtt-consumer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP