apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspi-simulator
  namespace: ot-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raspi-simulator
  template:
    metadata:
      labels:
        app: raspi-simulator
    spec:
      containers:
        - name: raspi-simulator
          image: ghcr.io/davidevaloroso-sys/ot-security:raspi-simulator-latest
          imagePullPolicy: Always
          env:
            - name: MODBUS_HOST
              value: "openplc"
            - name: MODBUS_PORT
              value: "502"
            - name: PUBLISH_INTERVAL
              value: "5"
            - name: DEVICE_NAME
              value: "raspi1"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"